discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["ves-hx-e3", "ves-hx-e4"]
#discovery.zen.minimum_master_nodes: 3
gateway.expected_nodes: 2
bootstrap.mlockall: true
cluster.name: gca_elasticsearch_staging
http.port: 9200
http.cors.enabled: true
action.disable_delete_all_indices: true
